### ISSUE TITLE
Gathering of Tweakers images won't load anymore since commit 0c70a72

### ISSUE THREAD

**Issue by iruoy** [EasyDutch-uBO/EasyDutch#35] opened 2023-01-30 19:25 UTC
### Prerequisites / Vereisten

- [X] This is a **Dutch** website / Het is een **Nederlandse** website
- [X] I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
- [X] Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
- [X] I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

https://gathering.tweakers.net/forum/list_messages/2168160

### Describe the issue

The images on [Gathering of Tweakers](https://gathering.tweakers.net/) posts won't load since this commit: [0c70a72](https://github.com/EasyDutch-uBO/EasyDutch/commit/0c70a726cd86c2c1b48394221f9a625a5ea18391)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/5859352/215575070-d4db8cb2-a4ab-42db-ab08-67b8e87ae2f6.png">

</details>

### Configuration / Configuratie

<details>
<summary>Troubleshooting Information / Probleemoplossingsinformatie</summary>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 86203
  cosmetic: 83021
  scriptlet: 21970
  html: 1012
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 45336-238, 17m
    ublock-annoyances: 4765-4, 17m
    NLD-0: 2568-24, 17m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33040-211, 17m
    ublock-badware: 4220-5, 17m
    ublock-privacy: 307-0, 17m
    ublock-abuse: 77-0, 17m
    ublock-unbreak: 1880-3, 17m
    ublock-quick-fixes: 533-0, 17m
    easylist: 61289-676, 17m
    easyprivacy: 30907-1741, 17m
    urlhaus-1: 6694-0, 17m
    plowe-0: 3669-2, 17m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
hostRuleset: 
  added: [array of 50 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 800 ms (selfie)
  maxAssetCacheWait: 166 ms
```
</details>

### Privacy

- [X] I agree to follow this condition / Ik ga akkoord met deze voorwaarde

**Comment by BPower0036** [comment] 2023-01-31 11:40
The problem lays not in this list but by EasyPrivacy blocking `||tweakers.net/*/?$image`
I will report it overthere.

**Comment by krystian3w** [comment] 2023-01-31 20:22
Duplicate of https://github.com/easylist/easylist/issues/14780

**Comment by JohnyP36** [comment] 2023-02-01 04:06
@iruoy If you update uBlock-Unbreak filter list the problem is solved. 
The added the rule `||tweakers.net/*/?$image,badfilter`.

**Comment by krystian3w** [comment] 2023-02-01 08:13
[crisp-tweakers](https://github.com/crisp-tweakers) detected: https://github.com/easylist/easylist/commit/8a99d705ab0d931ab90c53e383b48c51b5310168

So unbreak no longer match if isn't follow changes:
```adb
||tweakers.net/*/?$image
||tweakers.net/*/?$image,badfilter
||tweakers.net/*/?url$image
! ?     ?      ?          ?,badfilter
```

**Closed** 2023-02-02 07:30 UTC
