### ISSUE TITLE
Tweakers Top banner

### ISSUE THREAD

**Issue by Ziglar1** [EasyDutch-uBO/EasyDutch#22] opened 2022-06-02 06:37 UTC
### Prerequisites / Vereisten

- [X] This is a **Dutch** website / Het is een **Nederlandse** website
- [X] I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
- [X] Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
- [X] I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

https://tweakers.net/

### Describe the issue

big ad on top of the page and on side of the page

![Schermafbeelding 2022-06-02 083338](https://user-images.githubusercontent.com/17732290/171568143-ce0a6553-6702-490e-a77e-461f6b2f77a7.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration / Configuratie

<details>
<summary>Troubleshooting Information / Probleemoplossingsinformatie</summary>

```yaml
```
</details>

### Notes

updated the ublock. 
updated google chrome
cleared cache
searched online
easydutch filter is active

### Privacy

- [X] I agree to follow this condition / Ik ga akkoord met deze voorwaarde

**Comment by JohnyP36** [comment] 2022-06-02 08:30
The banner that's shown in your screenshot, if you click on it will it open mediamarkt.nl or tweakers.net? 

##### Note: this issue was marked invalid and closed by the bot, because you forgot to remove the line under `configuration` that says `<!-- Put the copied text here, by replacing this line / Zet hier de gekopieerde tekst neer, door deze regel te overschrijven -->`. Next time remove or replace with uBo info

**Comment by Ziglar1** [comment] 2022-06-02 08:43
@JohnyP36 the add will open a redirection within tweakers.
when i put the following 2 addresses in "my filters" the adds will dissapear. 
maybe block them by default ?

aa.tweakers.nl
ab.tweakers.nl

**Comment by JohnyP36** [comment] 2022-06-02 08:46
> @JohnyP36 the add will open a redirection within tweakers. when i put the following 2 addresses in "my filters" the adds will dissapear. maybe block them by default ?
> 
> aa.tweakers.nl ab.tweakers.nl

Yah, I saw that they don't have 3p ads anymore. I verified that `ab.tweakers.net` is for ads. Only have to reproduce the `aa.`

**Closed** 2022-06-02 09:06 UTC
